### ISSUE TITLE
Question: are you suppose to check in the cache file that lazy creates?

### ISSUE THREAD

**Issue by Aghassi** [forcedotcom/sfdx-dev-packages#64]
I've started using https://www.npmjs.com/package/@salesforce/lazy-require in one of my OClif CLIs, and would like to clarify if my users should check in the cache file generated. I'm assuming "no" is the answer since that is what ESLint recommends for their stuff, but wanted to be sure. The docs are _very_ sparse so I have no idea if I even set this thing up right. 

@amphro if you have any insights please let me know :)

**Comment by rbergman** [comment]
Sorry for the late reply here, but no do not check in that file.  It will be regenerated on demand.
